/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.*;
import java.net.ConnectException;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author pc
 */
public class Login extends javax.swing.JFrame {
    static String email;
    /**
     * Creates new form Login
     */
    
    public Login() {
        initComponents();
        loginform.setBackground(new Color(25,1,1,160));
        setSize(1024,600);
        mail.requestFocus();
        SwingUtilities.getRootPane(login).setDefaultButton(login);
      
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbutton = new javax.swing.JButton();
        loginform = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Signup = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(new java.awt.Point(500, 200));
        setMinimumSize(new java.awt.Dimension(1024, 576));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbutton.setForeground(new java.awt.Color(204, 0, 0));
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-arrow-icon-63664.png"))); // NOI18N
        backbutton.setContentAreaFilled(false);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 60, 60));
        backbutton.getAccessibleContext().setAccessibleDescription("");

        loginform.setBackground(new java.awt.Color(255, 212, 0));
        loginform.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USER LOGIN");

        login.setBackground(new java.awt.Color(255, 102, 51));
        login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("Don't have an account?");

        Signup.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Signup.setForeground(new java.awt.Color(255, 255, 255));
        Signup.setText("Sign Up");
        Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Email");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("Password");

        pass.setEchoChar('\u2022');

        loginform.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginform.setLayer(login, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginform.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginform.setLayer(Signup, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginform.setLayer(mail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginform.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginform.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        loginform.setLayer(pass, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout loginformLayout = new javax.swing.GroupLayout(loginform);
        loginform.setLayout(loginformLayout);
        loginformLayout.setHorizontalGroup(
            loginformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginformLayout.createSequentialGroup()
                .addGroup(loginformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginformLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(loginformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mail, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(pass)))
                    .addGroup(loginformLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(loginformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(loginformLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(loginformLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(Signup))
                    .addGroup(loginformLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        loginformLayout.setVerticalGroup(
            loginformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginformLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(login)
                .addGap(88, 88, 88)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Signup)
                .addGap(76, 76, 76))
        );

        getContentPane().add(loginform, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 330, 470));

        jPanel3.setLayout(new javax.swing.OverlayLayout(jPanel3));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.jpg"))); // NOI18N
        jPanel3.add(jLabel2);

        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void SignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupMouseClicked
       setVisible(false);
       new Register().setVisible(true);
    }//GEN-LAST:event_SignupMouseClicked
  
    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        Welcome si=new Welcome();
        this.dispose();
        si.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed
    @SuppressWarnings( "deprecation" )
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try{
        String [] a={"login",mail.getText(),pass.getText()};
        email=mail.getText();
        
        Socket s=new Socket("localhost",5000);
        
        
        ObjectOutputStream out = new ObjectOutputStream(s.getOutputStream());
        ObjectInputStream oo=new ObjectInputStream(s.getInputStream());
       
        out.writeObject(a); 

        InputStreamReader i=new InputStreamReader(s.getInputStream());
        BufferedReader br=new BufferedReader(i);
        String message=br.readLine();
        
        System.out.println(message);
        if (message.equals("true")){
            
            this.setVisible(false);
        new Customer().setVisible(true);
        }
        else if (message.equals("admin")) {
        setVisible(false);
        new Admin().setVisible(true);
        }
        else if (message.equals("false"))
        {
            JOptionPane.showMessageDialog(this,"Incorrect Email or Password");
        }
        
        }
        catch(ConnectException e ){
            JOptionPane.showMessageDialog(this,"Cannot connect to server","Error",JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
        e.printStackTrace();
        }
       
    }//GEN-LAST:event_loginActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Signup;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton login;
    private javax.swing.JLayeredPane loginform;
    private javax.swing.JTextField mail;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
