/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.io.*;
import java.net.Socket;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class Register extends javax.swing.JFrame {
    boolean access1,access2,access3,access4,access5,access6,access7;
    /**
     * Creates new form Register1
     */
    public Register() {
        initComponents();
         
        
        setSize(1024,576);
      
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Fname = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        Contact = new javax.swing.JTextField();
        Cabin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cpass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pswd = new javax.swing.JPasswordField();
        f = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();
        ca = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setLocation(new java.awt.Point(500, 200));
        setMinimumSize(new java.awt.Dimension(1024, 576));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 576));
        getContentPane().setLayout(null);

        jLayeredPane1.setBackground(new java.awt.Color(255, 153, 102));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1024, 576));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(70, 120, 160, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(70, 170, 150, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-mail");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(70, 270, 130, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm password");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(50, 370, 190, 22);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(70, 420, 100, 22);

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Login);
        Login.setBounds(520, 200, 110, 31);

        Submit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Submit);
        Submit.setBounds(310, 470, 100, 31);

        Fname.setBackground(new java.awt.Color(204, 204, 204));
        Fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FnameKeyReleased(evt);
            }
        });
        jLayeredPane1.add(Fname);
        Fname.setBounds(250, 120, 185, 26);

        mail.setBackground(new java.awt.Color(204, 204, 204));
        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailKeyReleased(evt);
            }
        });
        jLayeredPane1.add(mail);
        mail.setBounds(250, 270, 185, 26);

        Contact.setBackground(new java.awt.Color(204, 204, 204));
        Contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ContactKeyReleased(evt);
            }
        });
        jLayeredPane1.add(Contact);
        Contact.setBounds(250, 420, 185, 25);

        Cabin.setBackground(new java.awt.Color(204, 204, 204));
        Cabin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CabinKeyReleased(evt);
            }
        });
        jLayeredPane1.add(Cabin);
        Cabin.setBounds(250, 220, 185, 26);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Register Yourself");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(270, 50, 197, 29);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Already have an account?");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(460, 170, 227, 22);

        cpass.setBackground(new java.awt.Color(204, 204, 204));
        cpass.setEchoChar('\u2022');
        cpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpassKeyReleased(evt);
            }
        });
        jLayeredPane1.add(cpass);
        cpass.setBounds(250, 370, 185, 25);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cabin No.");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(70, 220, 160, 20);

        Lname.setBackground(new java.awt.Color(204, 204, 204));
        Lname.setForeground(new java.awt.Color(21, 9, 9));
        Lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LnameKeyReleased(evt);
            }
        });
        jLayeredPane1.add(Lname);
        Lname.setBounds(250, 170, 185, 26);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(70, 320, 130, 22);

        pswd.setBackground(new java.awt.Color(204, 204, 204));
        pswd.setEchoChar('\u2022');
        pswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswdKeyReleased(evt);
            }
        });
        jLayeredPane1.add(pswd);
        pswd.setBounds(250, 320, 185, 25);

        f.setForeground(new java.awt.Color(244, 19, 19));
        jLayeredPane1.add(f);
        f.setBounds(250, 150, 160, 20);

        l.setForeground(new java.awt.Color(239, 3, 3));
        jLayeredPane1.add(l);
        l.setBounds(250, 200, 150, 20);

        cp.setForeground(new java.awt.Color(227, 3, 3));
        jLayeredPane1.add(cp);
        cp.setBounds(250, 400, 170, 20);

        ca.setForeground(new java.awt.Color(238, 4, 4));
        jLayeredPane1.add(ca);
        ca.setBounds(250, 250, 170, 20);

        c.setForeground(new java.awt.Color(248, 15, 15));
        jLayeredPane1.add(c);
        c.setBounds(250, 440, 180, 20);

        e.setForeground(new java.awt.Color(246, 13, 13));
        jLayeredPane1.add(e);
        e.setBounds(250, 300, 170, 20);

        password.setForeground(new java.awt.Color(246, 13, 13));
        jLayeredPane1.add(password);
        password.setBounds(250, 350, 300, 20);

        img.setForeground(new java.awt.Color(248, 11, 11));
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgregister.png"))); // NOI18N
        jLayeredPane1.add(img);
        img.setBounds(0, -10, 1024, 590);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 1024, 576);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
            
    
    private void FnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameKeyReleased
        // TODO add your handling code here:
         if(!(Pattern.matches("[A-za-z]{3,}", Fname.getText())))
           {
                 f.setText( "Invalid Firstname");
                 access1=false;
           }
         else{
             f.setText("");
             access1=true;
         }
    }//GEN-LAST:event_FnameKeyReleased

    private void LnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameKeyReleased
        // TODO add your handling code here:
        if(!(Pattern.matches("[A-za-z]{3,}", Lname.getText())))
          {
                 l.setText( "Invalid Lastname");
                 access2=false;
           }
         else{
             l.setText("");
            access2=true;
         }
    }//GEN-LAST:event_LnameKeyReleased

    private void CabinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CabinKeyReleased
        // TODO add your handling code here:
        try{
        if(!(Pattern.matches("^[0-9]", Cabin.getText()))&& Integer.parseInt(Cabin.getText())>50) 
        {
                 ca.setText( "Invalid Cabin No.");
                 access3=false;
           }
         else{
             ca.setText("");
             access3=true;
        }
        }
        catch(NumberFormatException nfe)
        {
            ca.setText( "Invalid Cabin No.");
        }
        
    }//GEN-LAST:event_CabinKeyReleased

    private void mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyReleased
        // TODO add your handling code here:
 
               if(!(Pattern.matches("^[a-zA-z]+[a-zA-Z0-9]+[@]+[a-zA-Z]+[.]+[com]+$", mail.getText()))) 
        {
                 e.setText( "Invalid Email");
                 access4=false;
           }
         else{
             e.setText("");
             access4=true;
        }
    }//GEN-LAST:event_mailKeyReleased

    private void ContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactKeyReleased
        // TODO add your handling code here:
         if(!(Pattern.matches("^[9][0-9]{9}" , Contact.getText())))
        {
                 c.setText( "Invalid Contact");
                 access5=false;
           }
         else{
             c.setText("");
             access5=true;
         }
    }//GEN-LAST:event_ContactKeyReleased
@SuppressWarnings("deprecation")
    private void cpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpassKeyReleased
        // TODO add your handling code here:
         if (!cpass.getText().equals(pswd.getText()))
        {
                 cp.setText( "Passwords do not match");
                 access6=false;
           }
         else{
             cp.setText("");
             access6=true;
         }
        
    }//GEN-LAST:event_cpassKeyReleased
@SuppressWarnings("deprecation")
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
         
    if(Fname.getText().isEmpty()|| Lname.getText().isEmpty()|| Cabin.getText().isEmpty()|| mail.getText().isEmpty()|| pswd.getText().isEmpty()|| cpass.getText().isEmpty()|| Contact.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Enter All Fields","Error", JOptionPane.ERROR_MESSAGE);  
        }
    else if(access1 && access2 && access3 && access4 && access5 && access6 && access7){
    String [] a={"register",Fname.getText(),Lname.getText(),Cabin.getText(),mail.getText(),cpass.getText(),Contact.getText()};
        try{
        Socket s=new Socket("localhost",5000);
        
        
        
        ObjectOutputStream out = new ObjectOutputStream(s.getOutputStream());
        ObjectInputStream oo=new ObjectInputStream(s.getInputStream());
        
        out.writeObject(a); 
        String []message=(String [])oo.readObject();
        
        out.close();
        if(message[0].equals("Cabin exists")){
                    JOptionPane.showMessageDialog(this,"Cabin is already being used","Error",JOptionPane.ERROR_MESSAGE);
                    
                }
        else if(message[0].equals("Email exists")) {
            JOptionPane.showMessageDialog(this,"Email already Exist","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(message[0].equals("success")) {
            JOptionPane.showMessageDialog(this,"Registeration Successful");
            this.setVisible(false);
            new Login().setVisible(true);
        }
       
        
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this,"Cabin doent exist","Error",JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
        e.printStackTrace();
        }
    }
    else{
        JOptionPane.showMessageDialog(null,"Please enter valid credentials","Error", JOptionPane.ERROR_MESSAGE);  
    }
    }//GEN-LAST:event_SubmitActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_LoginActionPerformed
    @SuppressWarnings("deprecation")
    private void pswdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswdKeyReleased
        if(!(Pattern.matches(".{8,}", pswd.getText())))
        {
                 password.setText( "Password must be atleast 8 characters");
                 access7=false;
           }
         else{
             password.setText("");
             access7=true;
         }
    }//GEN-LAST:event_pswdKeyReleased

    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cabin;
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JButton Login;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel c;
    private javax.swing.JLabel ca;
    private javax.swing.JLabel cp;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JLabel e;
    private javax.swing.JLabel f;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel l;
    private javax.swing.JTextField mail;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField pswd;
    // End of variables declaration//GEN-END:variables
}
