
package gui;


import java.awt.Color;

public class Welcome extends javax.swing.JFrame {


    public Welcome() {
        initComponents();
        setSize(1024,576); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Heading = new javax.swing.JLabel();
        Signup = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        Goal = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 576));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1024, 576));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1024, 576));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        Heading.setText("Welcome to Cruise Excursion");
        jLayeredPane1.add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 5, -1, -1));

        Signup.setText("Sign in");
        Signup.setBorder(null);
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 80, 30));

        Login.setText("Sign up");
        Login.setBorder(null);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 70, 30));

        Goal.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Goal.setText("\"Come Join with us to make your holiday enjoyable\"");
        jLayeredPane1.add(Goal, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 72, -1, -1));

        Description.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Description.setText("Reach countries,cities and place of interest in a short period of time.");
        jLayeredPane1.add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg1.png"))); // NOI18N
        image.setOpaque(true);
        jPanel2.add(image);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
       Register reg = new Register();
       this.dispose();
       reg.setVisible(true);
    }//GEN-LAST:event_LoginActionPerformed

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
       Login log = new Login();
       this.dispose();
       log.setVisible(true);
    }//GEN-LAST:event_SignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Goal;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton Login;
    private javax.swing.JButton Signup;
    private javax.swing.JLabel image;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
